DB:
  AutoCreateTable: true
  Driver: "mysql"
  DriverName: "dang"
  # Host: "118.178.180.247"
  Host: "localhost"
  Port: "3306"
  User: "root"
  # User: "cool"
  Password: "sa.com"
  # Password: "4KMCSR8DGGF58kW2"
  Charset: "utf8mb4"
Conf:
  AppName: "dang_go"
  Host: "127.0.0.1"
  Port: "87"
Alipay:
  AppId: "2021003186611052"
  RSA2048: "MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDX09Wtpu0AKg5lmNF0atz2bQgRYwgsjNnmWhela1lSWRIdR9DnqEYjxwu+pBnvCKVuQ8/CRDWCxUA8ucSrXuzipdIaHpHyNoyNMn2AJpeo2FydZYjGdKPuPTRhh8ZUaZhQYb0hqYAGOopFNxtiKCZVMibl7VNspUKJgxWItPZpNaK41wr4zumpdPsfXBte72GJahBqOcbcGOnbfl8mqvp3rGngK3yCV7o9gbD8PrOqEQ0/pz13SWSfgJeGZaIUNkmPZsBc9N5tbnQzLaBVcTmFRzxIXBwqIud5WM9PWyhq9OEH9sTUp3aRUA/tFxAWEqNuiQH3gUkkUVIyGO695lIfAgMBAAECggEAIajzAVMwUT894ZB00jA8Z95XTMbiJniNH0TbvTvBwXsMvS5PIWH4FmpbpY7YUJRLoKfIxiZ3Jf73ZsEeMA/s5+gunU45OspRH1BJjGv4aSfdQdrs+u6EBorbGX7gapfRXm/v3EkgI1iL6gGPLr7OQ6k/scpSoXYgq2ubNyfp6jxe3BwQLkNyWNqYjuBrmj7kHJFEaR9GbyPF3IC4PZafxFRje5czmLSlN4CsMbUAR+F1giayf2bzhumFXYXRCmY4U0OMT96E/f+Bj2U0aExox4dyIKbckE0GWnDgP00hUzRn6mUUnksRkMukZZavJ/lk+tRzO5R4BuuDtGQRKQGxyQKBgQDx3SXK17d7znxjl7b7hMjhVZ/xVSvW7HQfFkiVzhuQhqp+QzdgNlFu/UBne5GFHyMmOh7aVhbo5dk0fFcO8B26o/9syvMYEDByrKjcQc6v59z9KTUHV8XTFjlPdcJ+5OQ6eD01QcEawc7NnaU5UOr4AJLPCJrVe4cNI47a/crjwwKBgQDkcR8fQpaGUXekcSdhDnXJ+kxjf9xH/Ta2ec5ANXLNRuNRekWoO+N7NhbEC6eL8abCvTGCgqq1SRGaHYndTFbOP/0dbzi69IKrXjmIAK3oHeXVn53Fa5u0WOxjKtZvqG9/pOoM7AxOvV22mGcs8EVtDuZK+iDlIppD22AJDcE+dQKBgHICqib1CtP8oNwdjy7/B+ZYg32yhWjZq19gFLUxJAM7x7CfJMJguIBWNv7Q2+bhp6MEcLjBLil496trFWrAO3NYjTYOcQsdzoiv5SV2i+SVqrFXtFySvnjjl/5h514DraX2OfwZ09o2E7MPJexfvXNMaefYCYyqnx3NbjDCw9obAoGBANHyYP7yzLI/VyzLTby2dGyfW+sqDIIg5lLIGVULiim815f/PtuBxuxq5ntglqhX+8IH7OOcQVWBBOtV8GlxCmpdhruxhzrTEvB6FXe34Bxutdch7fcNkbkq7H2rVg6ih26RWwVrP1hyUxlIcbJsU/IJ+n636NmNdqeci2Nmv84tAoGAUS4Nn0RTTEwrJh14Ct+3NvtZCkVPyYIj4IIchW69pdSKO9nLzinJ7ZEQ3ijiXVDP1u1nv9G5U8ZHZ6+5xMsg/PRLZlcA6We5rE1tQiw6fs1t2mkWPCiyCRpXPDTM9QihLVT/jtwS1EeQJAEiaDKn469Pak1lkkDgaPag71FNL2k="
